import {
  BASE_CHECK_RUN_EVENT_MULTIPLE_PULL_REQUEST,
  BASE_CHECK_RUN_EVENT_SINGLE_PULL_REQUEST,
} from "./base";

const BASIC_CHECK_RUN_CREATED_EVENT_MULTIPLE_PULL_REQUEST =
  BASE_CHECK_RUN_EVENT_MULTIPLE_PULL_REQUEST;
BASIC_CHECK_RUN_CREATED_EVENT_MULTIPLE_PULL_REQUEST["action"] = "created";

const BASIC_CHECK_RUN_CREATED_EVENT_SINGLE_PULL_REQUEST =
  BASE_CHECK_RUN_EVENT_SINGLE_PULL_REQUEST;
BASIC_CHECK_RUN_CREATED_EVENT_SINGLE_PULL_REQUEST["action"] = "created";

export {
  BASIC_CHECK_RUN_CREATED_EVENT_MULTIPLE_PULL_REQUEST,
  BASIC_CHECK_RUN_CREATED_EVENT_SINGLE_PULL_REQUEST,
};
